# SVM 

# importing libraries

In [ ]:
import nltk
import re
import pandas as pd
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score

from sklearn.svm import SVC

In [ ]:
WNL = WordNetLemmatizer()
tfidf = TfidfVectorizer()

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# reading data from drive

In [ ]:
dataset = pd.read_csv("/content/drive/MyDrive/SMSSpamCollection.csv", sep = "\t", names = ["labels", "messages"])

In [ ]:
dataset

labels                                           messages
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567   spam  This is the 2nd time we have tried 2 contact u...
5568    ham               Will ü b going to esplanade fr home?
5569    ham  Pity, * was in mood for that. So...any other s...
5570    ham  The guy did some bitching but I acted like i'd...
5571    ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:
dataset.describe()

labels                messages
count    5572                    5572
unique      2                    5169
top       ham  Sorry, I'll call later
freq     4825                      30

# preprocessing

In [ ]:
nltk.download("all")

In [ ]:
corpus = []
for i in range(len(dataset)):
  data = re.sub('[^a-zA-Z]', " ", dataset["messages"][i])
  data = str.lower(data)
  data = nltk.word_tokenize(data)
  data = [WNL.lemmatize(word) for word in data if word not in stopwords.words("english")]
  data = " ".join(data)
  corpus.append(data)

In [ ]:
corpus

In [ ]:
X = tfidf.fit_transform(corpus).toarray()

In [ ]:
print(X.shape)

(5572, 7094)


In [ ]:
Y = pd.get_dummies(dataset["labels"])
Y

ham  spam
0       1     0
1       1     0
2       0     1
3       1     0
4       1     0
...   ...   ...
5567    0     1
5568    1     0
5569    1     0
5570    1     0
5571    1     0

[5572 rows x 2 columns]

In [ ]:
Y = Y.iloc[:, 1].values
Y

array([0, 0, 1, ..., 0, 0, 0], dtype=uint8)

In [ ]:
xtrain, xtest, ytrain, ytest = train_test_split(X, Y, test_size = 0.2, random_state=0)

In [ ]:
svm = SVC(kernel = "linear")
svm_model = svm.fit(xtrain, ytrain)

In [ ]:
predicted = svm_model.predict(xtest)

In [ ]:
cm = confusion_matrix(ytest, predicted)
acc = accuracy_score(ytest, predicted)

print(cm)
print(acc)

[[954   1]
 [ 17 143]]
0.9838565022421525


# ....

In [ ]:
# importing libraries
import nltk
import re
import pandas as pd
# import numpy as np
# from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
# from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC  # SVM

# creating objects

In [ ]:

# stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()
# cv = CountVectorizer()
tfidfv = TfidfVectorizer()

# reading data
download link --->  https://archive.ics.uci.edu/ml/machine-learning-databases/00228/smsspamcollection.zip

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/SMSSpamCollection.csv", sep="\t", names=["lable", "message"])

In [ ]:
data

In [ ]:
data.describe()

In [ ]:
nltk.download('stopwords')
stopwords.words("english")

# Data Preprocessing
- tokenization
- Punctuation removal
- stopwords removal
- lemmatization

In [ ]:
nltk.download('punkt')
nltk.download('wordnet')

In [ ]:
nltk.download('omw-1.4')

In [ ]:
corpus = []
for i in range(len(data)):
    words = re.sub('[^a-zA-Z]', ' ', data["message"][i])
    words = words.lower()
    words = nltk.word_tokenize(words)
    # words = nltk.word_tokenize(sentences[i])
    words = [lemmatizer.lemmatize(word) for word in words if word not in set(stopwords.words("english"))]
    words = ' '.join(words)
    corpus.append(words)

In [ ]:
corpus

# tfidf vectorizing

In [ ]:
X = tfidfv.fit_transform(corpus).toarray()

In [ ]:
print(X.shape)

(5572, 7094)


# assingning values to labeled data 

In [ ]:
Y = pd.get_dummies(data["lable"])
Y

In [ ]:
Y = Y.iloc[:, 1].values

# splitting data to training and testing set

In [ ]:
xtrain, xtest, ytrain, ytest = train_test_split(X, Y, random_state=0, test_size=0.2)

# SVM Model

In [ ]:
svc = SVC(kernel="linear")
model = svc.fit(xtrain, ytrain)

# prediction

In [ ]:
dtct = model.predict(xtest)

# checking accuracy

In [ ]:
cm = confusion_matrix(ytest, dtct)
acuuracy = accuracy_score(ytest, dtct)
print(acuuracy)
print(cm)

0.9838565022421525
[[954   1]
 [ 17 143]]


# NAIVE BAYES

In [ ]:
from sklearn.naive_bayes import MultinomialNB  # Naive bayes
# naive bayes algorithm for classification
MNN = MultinomialNB()
spam_detection_model = MNN.fit(xtrain, ytrain)

In [ ]:
# making predictions and checking accuracy score
detect = spam_detection_model.predict(xtest)
cm = confusion_matrix(ytest, detect)
acuuracy = accuracy_score(ytest, detect)
print(acuuracy)
print(cm)

0.9721973094170404
[[955   0]
 [ 31 129]]
